"""initial

Revision ID: 3bd7de8092a8
Revises: 
Create Date: 2021-08-21 14:57:08.843316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bd7de8092a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone_number', sa.CHAR(length=10), nullable=False),
    sa.Column('wallet_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index('clients_first_name', 'clients', ['first_name'], unique=False, postgresql_using='btree')
    op.create_index('clients_first_name_last_name', 'clients', ['first_name', 'last_name'], unique=False, postgresql_using='btree')
    op.create_index('clients_last_name', 'clients', ['last_name'], unique=False, postgresql_using='btree')
    op.create_table('operations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('benefactor_client_id', sa.BigInteger(), nullable=True),
    sa.Column('beneficiary_client_id', sa.BigInteger(), nullable=True),
    sa.Column('transfer_amount', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('operation_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['benefactor_client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['beneficiary_client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operations')
    op.drop_index('clients_last_name', table_name='clients', postgresql_using='btree')
    op.drop_index('clients_first_name_last_name', table_name='clients', postgresql_using='btree')
    op.drop_index('clients_first_name', table_name='clients', postgresql_using='btree')
    op.drop_table('clients')
    # ### end Alembic commands ###
